# Generated by Django 4.1.5 on 2023-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0003_habilidad_programador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidad',
            old_name='comentario',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Programador',
        ),
    ]
