# Generated by Django 4.1.5 on 2023-12-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0004_rename_comentario_habilidad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
