# Generated by Django 4.1.5 on 2023-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0006_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_inicio', models.CharField(max_length=4)),
                ('anio_fin', models.CharField(max_length=4)),
                ('grado', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='estudios/')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['anio_inicio', 'anio_fin', 'grado', 'imagen'],
            },
        ),
    ]
