# Generated by Django 4.1.5 on 2023-12-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0007_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seguidor')),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'seguidores',
                'ordering': ['seguidor'],
            },
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={'ordering': ['id', 'fecha_inicio', 'fecha_fin', 'nota_media', 'nivelEstudio'], 'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='anio_fin',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='anio_inicio',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_fin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='nivelEstudio',
            field=models.CharField(default=0.0004943153732081067, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='nota_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Seguido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguido', to='appportfolio.seguido')),
            ],
            options={
                'verbose_name': 'Seguido',
                'verbose_name_plural': 'Seguidos',
                'ordering': ['id', 'seguido'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('Notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='appportfolio.notificacion')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['id', 'Notificacion', 'fecha'],
            },
        ),
    ]
